travis:
  secure:
    BINSTAR_TOKEN: o+07GmeLs7qYX2jiwq67dFLoHphV40QdY3I89dbOI8xhDNDOTH2XJx1bbRIFqmL+/i1VmwVTvZCXgyV29ju5XrmMx0ckJwb1RK97MQTeo0+EJ+ubXInmB1XsJy0dUU2C04m3UMmbbj8X8Da3MA0NK0YPqkbHj8vbgbEBxpW0rnMMT47jzq4bRdtr45KG5oWcGL0ZV/zNBm+VQ3QCgQsItWqWQ/jiiRYqCyW+DOzJ6152JCZqh/B+X+URG4ep0a++kFcXK3nAhcAeQdvTaGW15tIF+rsvRmF0bdIqfKfqoWRTfj3656J9xxLsCwvuJ0vLROCgZmbQabeL/21/yE3zOvrA524YeHFqw11AAuwp4TIMfFYNHrcibGGzFWmOz2muxelAvZJcOqhk7yuBqRsjvgKl4Zi0eSUxsopcujzxk4MdhmVLrPheafDqsgFs8VoM/J7hbTuQO3kqPbTUWBIOImM0SrFabc02aZxSEyeLyYivIhYy/LmonrsiWRLstp8xt/BKabJjiMEsbGlYg4c7Pz0LuK8WmMuQQTejjmkLpDKJ4hb6fzhmFOInn6so+PAcA3gftFSiiOkDS+/bId9CMi6YQDfu1Ba9QtpcoyufV6JEHPDlj3JvJu8LQ5AferYdrOYEtqNv3aLs3MO7YvFnJR0NBoYJO6UvKB1bz+YrmUc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
